version: '3.8'
services:
  map0:
    build:
      context: ./Node/
      dockerfile: Configuration/Dockerfile
    container_name: Map0
    restart: always
    ports:
      - 4300:80
    environment:
      NODE_NAME: map0
      TYPE: map
      BROKER_PORT: 32769
      MASTER: true
      MAP_ROUTING_KEYS: 'command/map0,command/map1,command/map2,command/map3'
      MAP_ROUTING_KEY: command/map0
      MAP_FINISHED_EVENT_ROUTING_KEY: event/map/terminated
      MAP_SHUFFLE_ROUTING_KEY: command/shuffle
      REDUCE_ROUTING_KEYS: 'command/reduce0,command/reduce1,command/reduce2'
      INPUT_ROUTING_KEY: command/input
      SYNC_STORE_PAIR_PORT_LIST: 4300,4301,4302,4303,4304,4305,4306 # remove self..... 
    depends_on:
      - broker
  map1:
    build:
      context: ./Node/
      dockerfile: Configuration/Dockerfile
    container_name: Map1
    restart: always
    ports:
      - 4301:80
    environment:
      NODE_NAME: map1
      TYPE: map
      BROKER_PORT: 32769
      MAP_ROUTING_KEY: command/map1
      MAP_FINISHED_EVENT_ROUTING_KEY: event/map/terminated
      SYNC_STORE_PAIR_PORT_LIST: 4300,4301,4302,4303,4304,4305,4306s
    depends_on:
      - broker
  map2:
    build:
      context: ./Node/
      dockerfile: Configuration/Dockerfile
    container_name: Map2
    restart: always
    ports:
      - 4302:80
    environment:
      NODE_NAME: map2
      TYPE: map
      BROKER_PORT: 32769
      MAP_ROUTING_KEY: command/map2
      MAP_FINISHED_EVENT_ROUTING_KEY: event/map/terminated
      SYNC_STORE_PAIR_PORT_LIST: 4300,4301,4302,4303,4304,4305,4306
    depends_on:
      - broker
  map3:
    build:
      context: ./Node/
      dockerfile: Configuration/Dockerfile
    container_name: Map3
    restart: always
    ports:
      - 4303:80
    environment:
      NODE_NAME: map3
      TYPE: map
      BROKER_PORT: 32769
      MAP_ROUTING_KEY: command/map3
      MAP_FINISHED_EVENT_ROUTING_KEY: event/map/terminated
      SYNC_STORE_PAIR_PORT_LIST: 4300,4301,4302,4303,4304,4305,4306
    depends_on:
      - broker
  reducer0:
    build:
      context: ./Node/
      dockerfile: Configuration/Dockerfile
    container_name: Reducer0
    restart: always
    environment:
      NODE_NAME: reduce0
      MASTER: true
      TYPE: reduce
      BROKER_PORT: 32769
      INPUT_ROUTING_KEY: command/input
      REDUCE_ROUTING_KEY: command/reduce0
      REDUCE_FINISHED_EVENT_ROUTING_KEY: event/reduce/terminated
      SYNC_STORE_PAIR_PORT_LIST: 4300,4301,4302,4303,4304,4305,4306
      NB_OF_ITERATION: 1
    ports:
      - 4304:80
    depends_on:
      - broker
  reducer1:
    build:
      context: ./Node/
      dockerfile: Configuration/Dockerfile
    container_name: Reducer1
    restart: always
    environment:
      NODE_NAME: reduce1
      TYPE: reduce
      BROKER_PORT: 32769
      REDUCE_ROUTING_KEY: command/reduce1
      REDUCE_FINISHED_EVENT_ROUTING_KEY: event/reduce/terminated
      SYNC_STORE_PAIR_PORT_LIST: 4300,4301,4302,4303,4304,4305,4306
    ports:
      - 4305:80
    depends_on:
      - broker
  reducer2:
    build:
      context: ./Node/
      dockerfile: Configuration/Dockerfile
    container_name: Reducer2
    restart: always
    environment:
      NODE_NAME: reduce2
      TYPE: reduce
      BROKER_PORT: 32769
      REDUCE_ROUTING_KEY: command/reduce2
      REDUCE_FINISHED_EVENT_ROUTING_KEY: event/reduce/terminated
      SYNC_STORE_PAIR_PORT_LIST: 4300,4301,4302,4303,4304,4305,4306
    ports:
      - 4306:80
    depends_on:
      - broker
  broker:
    build:
      context: ./Broker/
      dockerfile: Configuration/Dockerfile
    container_name: Broker
    restart: always
    ports:
      - 32769:32769
    