version: '3.8'
services:
  receiver:
    build:
      context: ./Receiver/
      dockerfile: Receiver/Dockerfile
    container_name: Receiver0
    restart: always
    ports:
      - 4300:80
    environment:
      RoutingKey: weather/montreal/temperature
    depends_on:
      - broker
  receiver1:
    build:
      context: ./Receiver/
      dockerfile: Receiver/Dockerfile
    container_name: Receiver1
    restart: always
    ports:
      - 4301:80
    environment:
      RoutingKey: weather/montreal/temperature
    depends_on:
      - broker
  receiver2:
    build:
      context: ./Receiver/
      dockerfile: Receiver/Dockerfile
    container_name: Receiver2
    restart: always
    ports:
      - 4302:80
    environment:
      RoutingKey: weather/montreal/*
    depends_on:
      - broker
  receive3:
    build:
      context: ./Receiver/
      dockerfile: Receiver/Dockerfile
    container_name: Receiver3
    restart: always
    ports:
      - 4303:80
    environment:
      RoutingKey: '*'
    depends_on:
      - broker
  publisher:
    build:
      context: ./Publisher/
      dockerfile: Configuration/Dockerfile
    container_name: publisher
    restart: always
    ports:
      - 4304:80
    depends_on:
      - broker
  broker:
    build:
      context: ./Broker/
      dockerfile: Configuration/Dockerfile
    container_name: Broker
    restart: always
    ports:
      - 32769:32769
    