//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Configuration.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Configuration.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to width(pixel);price($)
        ///104;162
        ///291;349
        ///271;329
        ///282;340
        ///255;313
        ///154;212
        ///116;174
        ///117;175
        ///131;189
        ///275;333
        ///127;185
        ///201;259
        ///194;252
        ///204;262
        ///159;217
        ///273;331
        ///232;290
        ///150;208
        ///195;253
        ///275;333
        ///212;270
        ///260;318
        ///168;226
        ///105;163
        ///142;200
        ///229;287
        ///204;262
        ///95;153
        ///169;227
        ///299;357
        ///253;311
        ///119;177
        ///204;262
        ///59;117
        ///271;329
        ///127;185
        ///213;271
        ///81;139
        ///209;267
        ///228;286
        ///185;243
        ///239;297
        ///114;172
        ///283;341
        ///73;131
        ///134;192
        ///236;294
        ///295;353
        ///132;190
        ///201;259
        ///248;306
        ///214;272
        ///64;122
        ///187;245
        ///226;284        /// [rest of string was truncated]&quot;;.
        /// </summary>
        public static string data {
            get {
                return ResourceManager.GetString("data", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to group_id;barycenter
        ///#1;&lt;50,100&gt;
        ///#2;&lt;100,150&gt;
        ///#3;&lt;150,200&gt;
        ///#4;&lt;200,250&gt;
        ///#5;&lt;250,300&gt;
        ///.
        /// </summary>
        public static string groups {
            get {
                return ResourceManager.GetString("groups", resourceCulture);
            }
        }
    }
}
